.PHONY: clean All

All:
	@echo "----------Building project:[ FS_make_kgrid - Debug ]----------"
	@cd "FS_make_kgrid" && "$(MAKE)" -f  "FS_make_kgrid.mk"
clean:
	@echo "----------Cleaning project:[ FS_make_kgrid - Debug ]----------"
	@cd "FS_make_kgrid" && "$(MAKE)" -f  "FS_make_kgrid.mk" clean
